using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ModelBuilderApi.Entity
{
    
    public class CompanyInfo
    {
        
        public string COMPANY_CODE { get; set; }
        
        public string COMPANY_NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string? ADDRESS2 { get; set; }
        public string POSTAL_CODE { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public string OWNER_NAME { get; set; }
        public string? VATREGNO { get; set; }
        public string? TIN { get; set; }
        public string? TRADE_LICENSE_NO { get; set; }
        public string? DRUG_LICENSE_NO { get; set; }
        public string CONTACT_NO { get; set; }
        public string EMAIL { get; set; }
        public string? WEBSITE { get; set; }
        public string? PREFIX { get; set; }
        public DateTime DOE { get; set; }
        public DateTime DATE_OF_EXPIRE { get; set; }
        public decimal NUM_OF_STORE { get; set; }
        public decimal NUM_OF_USER { get; set; }
        public decimal CENTRALSTOREENABLED { get; set; }
        public decimal CENTRALSTORESALE { get; set; }
        public decimal SALE_VAT_PRCNT { get; set; }
        public decimal CREDIT_SALES_ALLOW { get; set; }
        public decimal NUM_OF_TERMINAL { get; set; }
        public decimal BARCODE_LEN { get; set; }
        public string? LOGO_URL { get; set; }
        public decimal INV_TPL_ID { get; set; }
        public decimal PO_TPL_ID { get; set; }
        public decimal PR_TPL_ID { get; set; }
        public string STATUS { get; set; }
        public string ENTRY_BY { get; set; }
        public DateTime ENTRY_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public DateTime UPDATED_DATE { get; set; }
        public string? BARCODE_PRINT_OPT { get; set; }
        public decimal? MP_ENABLED { get; set; }
        public bool? MEM_CRD_ENABLED { get; set; }
        public bool? GIFT_VOUCHER_ENABLED { get; set; }
        public decimal PUR_VAT_PRCNT { get; set; }
        public bool IS_PRICE_INCLD_VAT { get; set; }
        public bool IS_SUB_CAT_WISE_VARIANCE { get; set; }
        public bool IS_SHOP_WISE_SAL_PRICE { get; set; }
        public bool IS_VAT_BEFORE_DISC { get; set; }
        public bool IS_CUSTOMER_WISE_PRICE { get; set; }
        public bool IS_OVERWRITE_CD { get; set; }
        public bool IS_BRAND_WISE_STORE { get; set; }
        public decimal MIN_PROFIT_MAR_DISC { get; set; }
        public bool SHOW_DEPARTMENT { get; set; }
        public bool ALLOW_CARTONWISE_SALE { get; set; }
        public bool CPU_CHANGE_ON_RECEIVE { get; set; }
        public bool MRP_CHANGE_ON_RECEIVE { get; set; }
        public bool VENDOR_APPROVAL { get; set; }
        public bool STORE_REQ_APPROVAL { get; set; }
        public bool PO_APPROVAL { get; set; }
        public bool PUR_RCV_APPROVAL { get; set; }
        public bool WH_DELIVERY_APPROVAL { get; set; }
        public bool STR_DELIVERY_APPROVAL { get; set; }
        public bool DML_APPROVAL { get; set; }
        public bool PUR_RTN_APPROVAL { get; set; }
        public bool PRICE_CHANGE_APPROVAL { get; set; }
        public bool PROMOTION_APPROVAL { get; set; }
        public bool? IS_SUB_SUBCAT_WISE_VARIANCE { get; set; }
        public bool SHOW_SUB_SUBCATEGORY { get; set; }
        public string DEPARTMENT_LABEL { get; set; }
        public string SUB_DEPARTMENT_LABEL { get; set; }
        public string CATEGORY_LABEL { get; set; }
        public string SUB_CATEGORY_LABEL { get; set; }
        public string SUB_SUBCATEGORY_LABEL { get; set; }
        public bool SHOW_CONSOLE { get; set; }
        public string? SDC_VAT_CODE { get; set; }
        public string? SDC_SD_CODE { get; set; }
        public string? SDC_PKG_VAT_CODE { get; set; }
        public string? SDC_PKG_SD_CODE { get; set; }
        public bool? IS_MANUFACTURER_REQUIRED { get; set; }
        public bool? IS_STYLE_CODE_REQUIRED { get; set; }
        public bool? IS_MANAGE_ARTICLE { get; set; }
        public bool? IS_BATCHWISE_RECEIVE { get; set; }
        public bool? ALLOW_MANUAL_BATCH_INPUT { get; set; }
        public bool? MANAGE_VENDORWISE_STOCK { get; set; }
        public bool? IS_IMEI_ENABLED { get; set; }
        public bool? BNK_COMM_RDC_ON_SAL_RTN { get; set; }
        public bool? VENDOR_ACCT_HEAD_ENABLED { get; set; }
        public string? VENDOR_ACCT_HEAD { get; set; }
        public bool? MRP_CHANGE_ON_PO { get; set; }
        public bool? MANAGE_DONORWISE_STOCK { get; set; }
        public string AREA_LABEL { get; set; }
        public bool PRINT_DELIVERY_PICK_LIST { get; set; }
        public bool IS_RANDOM_GV_SERIAL { get; set; }
        public int GV_SERIAL_LEN { get; set; }
        public bool? POINT_REDEEMP_OTP { get; set; }
        public bool? GV_REDEEMP_OTP { get; set; }
        public bool? SMS_ON_INVOICE { get; set; }
        public bool? SMS_INCLD_INV_NO { get; set; }
        public bool? SMS_INCLD_INV_AMT { get; set; }
        public bool? SMS_INCLD_EARN_POINT { get; set; }
        public bool? SMS_INCLD_REDEEMED_POINT { get; set; }
        public string? SMS_TEMPLATE { get; set; }
        public bool VENDOR_WISE_CHALLAN_SL { get; set; }
        public bool CUSTOMER_REQ_ON_SALE { get; set; }
        public string CUSTOMER_TYPE_LABEL { get; set; }
        public string PRODUCT_NAME_LABEL { get; set; }
        public string PACK_SIZE_LABEL { get; set; }
        public string STYLE_CODE_LABEL { get; set; }
        public bool MANAGE_PV_USER_BARCODE { get; set; }
        public bool FIFO_METHOD { get; set; }
        public bool ThirdPartyCreditCustomerEnable { get; set; }
        public string? ThridPartyCCFor { get; set; }
        public string? ThirdPartyCC_Url { get; set; }
        public bool CUSTOMER_DISC_OTP_REQUIRED { get; set; }
        public bool IS_BATCH_AUTO_SERIAL { get; set; }
        public bool IS_REASON_TEXT { get; set; }
        public bool IS_SHOW_VEHICLE_IN_DELIVERY { get; set; }
        public bool? ENABLE_EXCESS_CREDIT_LIMIT { get; set; }
        public bool IS_REPRINT_DELIVERT_ORDER { get; set; }
        public bool IS_REPRINT_ALLOCATION_CHALLAN { get; set; }
        public bool IS_REPRINT_GIFT_VOUCHER_GEN_CHALLAN { get; set; }
        public bool ALLOW_PUR_DISCOUNT_CPU { get; set; }
        public bool IS_ECOM_AUTO_TRANSFER { get; set; }
        public bool IS_STORE_WISE_ORDER_LOADING { get; set; }
        public bool IS_MULTIPLE_MRP { get; set; }
        public bool IS_AUTO_SCAN_RECEIVE { get; set; }
        public bool MULTI_VEN_NOT_VEN_WISE_STOCK { get; set; }
        public bool IS_RCV_CHALLAN_STORE_DELIVERY { get; set; }
        public bool IS_TRNS_RCV_CHALLAN_STORE_DELIVERY { get; set; }
        public bool PRODUCT_APPROVAL { get; set; }
        public bool VAT_INCLUDING_BARCODE { get; set; }
        public bool IS_SHOW_QRCODE_PRINT { get; set; }
        public bool RECEIVE_CHALLAN_AUTO_DELIVERY { get; set; }
        public bool MULTIPLE_VENDOR { get; set; }
        public bool CPU_CHECKING_IN_STORE_DELIVERY { get; set; }
        public bool SAL_BARCODE_WISE_PRICE_CHANGE { get; set; }
        public bool CRM_ENABLE { get; set; }
        public string? CRM_FOR { get; set; }
        public string? CRM_URL { get; set; }
        public string? CRM_USER { get; set; }
        public string? CRM_PASS { get; set; }
        public string MAIN_CHANNEL_LABEL { get; set; }
        public string ZONE_LABEL { get; set; }
        public string CUSTOMER_GROUP_LABEL { get; set; }
        public string CUSTOMER_CATEGORY_LABEL { get; set; }
        public string CUSTOMER_SUB_CATEGORY_LABEL { get; set; }
        public bool DELIVERY_MAN_IN_STORE_DELIVERY { get; set; }
        public bool REF_NO_IN_STORE_DELIVERY { get; set; }
        public string SOFTWARE_VERSION { get; set; }
        public bool SMS_ON_GV_SALE { get; set; }
        public bool SMS_GV_INCLD_INV_NO { get; set; }
        public string? SMS_GV_TEMPLATE { get; set; }
        public bool SHOP_CONNECTION_CHECK { get; set; }
        public bool DIRECT_RECEIVE { get; set; }
        public bool CPU_EDIT_ON_PUR_RTN { get; set; }
        public bool REF_REQ_PUR_RCV { get; set; }
        public bool PO_EMAIL { get; set; }
        public bool STORE_WISE_CUSTOMER_ON_SALE { get; set; }
        public bool CPU_EDIT_ON_DMG_LOST { get; set; }
        public bool RabbitMQ { get; set; }
        public bool EC_OREDR_EDIT_BEFORE_DELIVERY { get; set; }
        public bool CPU_CHECK_ON_CIRCULAR_PRICE_CHANGE { get; set; }
        public bool VENDOR_CODE_SHOW_VENDOR_DD { get; set; }
        public bool SAL_VAT_PERCENT_IN_CATEGORY { get; set; }
        public bool SAL_VAT_PERCENT_IN_SUB_SUBCATEGORY { get; set; }
        public bool FLEX_ORDER_PROCESS { get; set; }
        public bool VENDOR_WISE_USER_BARCODE { get; set; }
        public bool Courier_Selection_on_Order_Created { get; set; }
        public string BRAND_LABEL { get; set; }
        public bool Store_Select_on_Order { get; set; }
        public bool OrderMargetoDelivery { get; set; }
        public bool OrderCreatetoReq { get; set; }
        public bool CusAccountsHeadCreation { get; set; }
        public bool SupAccountsHeadCreation { get; set; }
        public bool SimpleQuickSearch { get; set; }
        public bool ReasonTextRequired { get; set; }
        public bool SHOW_CUSTOMER_CATEGORY { get; set; }
        public bool SHOW_SHOPTYPE { get; set; }
        public bool PUR_RCV_SHOP { get; set; }
        public bool ENABLE_PHARMACY_COLLECTION_BOOTH { get; set; }
        public bool PRODUCT_WISE_DISCOUNT { get; set; }
        public bool InvoiceUrlSms { get; set; }
        public int RELEASE_VERSION { get; set; }
        public bool CATEGORY_WISE_COST_PRICE_CHANGE { get; set; }
        public bool EFFECT_PRICE_CHANGE_ALL_TRANSECTION { get; set; }
        public bool MAIL_SENDING_IN_CUSTOMER_PRICE_SETUP { get; set; }
        public bool SMS_ON_PURCHASE_ORDER { get; set; }
        public bool CATEGORY_WISE_CIRCULAR_DISCOUNT { get; set; }
        public string CRM_PASSWORD { get; set; }
        public bool CircularDiscountV2 { get; set; }
        public bool DAY_CLOSE { get; set; }
        public bool IsOrderTypeDefault { get; set; }
    }
}
